# Generated by Django 4.2.23 on 2025-09-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=200, null=True)),
                ('serial', models.CharField(max_length=200, null=True)),
                ('change_date', models.CharField(max_length=200, null=True)),
                ('part_number', models.IntegerField(default=0, null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('diesel', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel_name', models.CharField(max_length=100, null=True, verbose_name='اسم دیزل')),
                ('failure_title', models.CharField(max_length=200, null=True, verbose_name='عنوان خرابی')),
                ('failure_description', models.TextField(null=True, verbose_name='شرح خرابی')),
                ('start_date', models.CharField(max_length=10, null=True, verbose_name='تاریخ شروع خرابی')),
                ('end_date', models.CharField(max_length=10, null=True, verbose_name='تاریخ پایان خرابی')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='مکان خرابی')),
                ('repair_description', models.TextField(null=True, verbose_name='رفع خرابی')),
                ('officer', models.CharField(max_length=100, null=True, verbose_name='مامور خرابی')),
                ('in_repair', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تعمیرات',
                'verbose_name_plural': 'تعمیرات\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance/', verbose_name='تصویر')),
                ('image_type', models.CharField(choices=[('before', 'قبل از تعمیر'), ('after', 'بعد از تعمیر')], max_length=10, verbose_name='نوع تصویر')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenance')),
            ],
            options={
                'verbose_name': 'تصویر تعمیرات',
                'verbose_name_plural': 'تصاویر تعمیرات',
            },
        ),
    ]
