# Generated by Django 5.2.1 on 2025-05-17 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel_name', models.CharField(max_length=100, verbose_name='اسم دیزل')),
                ('failure_title', models.CharField(max_length=200, verbose_name='عنوان خرابی')),
                ('failure_description', models.TextField(verbose_name='شرح خرابی')),
                ('start_date', models.CharField(max_length=10, verbose_name='تاریخ شروع خرابی')),
                ('end_date', models.CharField(max_length=10, verbose_name='تاریخ پایان خرابی')),
                ('location', models.CharField(max_length=200, verbose_name='مکان خرابی')),
                ('symptoms', models.TextField(verbose_name='علائم خرابی')),
                ('officer', models.CharField(max_length=100, verbose_name='مامور خرابی')),
                ('in_repair', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تعمیرات',
                'verbose_name_plural': 'تعمیرات\u200cها',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance/', verbose_name='تصویر')),
                ('image_type', models.CharField(choices=[('before', 'قبل از تعمیر'), ('after', 'بعد از تعمیر')], max_length=10, verbose_name='نوع تصویر')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenance')),
            ],
            options={
                'verbose_name': 'تصویر تعمیرات',
                'verbose_name_plural': 'تصاویر تعمیرات',
            },
        ),
    ]
