# Generated by Django 5.2.7 on 2025-10-21 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('BOGIE_CHASSIS', 'Bogie and Chassis'), ('BRAKE', 'Brake'), ('CABIN_AMENITIES', 'Cabin and Amenities')], max_length=50, verbose_name='Damage Type')),
                ('description', models.TextField(verbose_name='Failure Description')),
                ('location', models.CharField(max_length=100, verbose_name='Failure Location')),
                ('reported_date', models.DateField(default=django.utils.timezone.now, verbose_name='Reported Date')),
                ('reported_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Reported Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Failure',
                'verbose_name_plural': 'Failures',
            },
        ),
        migrations.CreateModel(
            name='FailureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.failure', verbose_name='Failure')),
            ],
            options={
                'verbose_name': 'Failure Image',
                'verbose_name_plural': 'Failure Images',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Incident Description')),
                ('incident_date', models.DateField(default=django.utils.timezone.now, verbose_name='Incident Date')),
                ('incident_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Incident Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.incident', verbose_name='Incident')),
            ],
            options={
                'verbose_name': 'Incident Image',
                'verbose_name_plural': 'Incident Images',
            },
        ),
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locomotive_id', models.CharField(max_length=50, unique=True, verbose_name='Locomotive ID')),
                ('model', models.CharField(max_length=100, verbose_name='Locomotive Model')),
                ('depot', models.CharField(max_length=100, verbose_name='Depot Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Locomotive',
                'verbose_name_plural': 'Locomotives',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Repair Title')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('location', models.CharField(max_length=100, verbose_name='Repair Location')),
                ('technician', models.CharField(max_length=100, verbose_name='Technician')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20, verbose_name='Repair Status')),
                ('description', models.TextField(verbose_name='Repair Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Repair',
                'verbose_name_plural': 'Repairs',
            },
        ),
        migrations.CreateModel(
            name='RepairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Repair Image',
                'verbose_name_plural': 'Repair Images',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.TextField(verbose_name='Checklist Details')),
                ('serviced_date', models.DateField(default=django.utils.timezone.now, verbose_name='Serviced Date')),
                ('serviced_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Serviced Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='maintenance.locomotive', verbose_name='Locomotive')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
            },
        ),
        migrations.DeleteModel(
            name='ChangeParts',
        ),
        migrations.RemoveField(
            model_name='maintenanceimage',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='incident',
            name='locomotive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='maintenance.locomotive', verbose_name='Locomotive'),
        ),
        migrations.AddField(
            model_name='failure',
            name='locomotive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='maintenance.locomotive', verbose_name='Locomotive'),
        ),
        migrations.AddField(
            model_name='repair',
            name='failure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='maintenance.failure', verbose_name='Related Failure'),
        ),
        migrations.AddField(
            model_name='repairimage',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.repair', verbose_name='Repair'),
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='MaintenanceImage',
        ),
    ]
