# Generated by Django 5.2.1 on 2025-05-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='diesel_name',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم دیزل'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='end_date',
            field=models.CharField(max_length=10, null=True, verbose_name='تاریخ پایان خرابی'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='failure_description',
            field=models.TextField(null=True, verbose_name='شرح خرابی'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='failure_title',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان خرابی'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='مکان خرابی'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='officer',
            field=models.CharField(max_length=100, null=True, verbose_name='مامور خرابی'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='start_date',
            field=models.CharField(max_length=10, null=True, verbose_name='تاریخ شروع خرابی'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='symptoms',
            field=models.TextField(null=True, verbose_name='علائم خرابی'),
        ),
    ]
