# Generated by Django 5.2.1 on 2025-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_diesel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='repair_description',
            field=models.TextField(null=True, verbose_name='رفع خرابی'),
        ),
    ]
