# Generated by Django 5.2.7 on 2025-10-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_failure_failureimage_incident_incidentimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='inRepair',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
