# Generated by Django 5.2.1 on 2025-05-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_maintenance_symptoms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=200, null=True)),
                ('serial', models.CharField(max_length=200, null=True)),
                ('change_date', models.CharField(max_length=200, null=True)),
                ('part_number', models.IntegerField(default=0, null=True)),
                ('product_id', models.IntegerField(null=True)),
            ],
        ),
    ]
