# Generated by Django 5.2.7 on 2025-10-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_failure_inrepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hasOil',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
