# Generated by Django 5.2.1 on 2025-05-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_changeparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeparts',
            name='diesel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
