# Generated by Django 5.2.7 on 2025-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_service_hasoil'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='dispatch_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اعزام نیرو از'),
        ),
        migrations.AddField(
            model_name='failure',
            name='move_status',
            field=models.CharField(choices=[('ACTIVE', 'گرم / ادامه سیر'), ('DEACTIVE', 'سرد'), ('REPAIR', 'متوقف / اعزام به تعمیرات')], default='ACTIVE', max_length=20, verbose_name='وضعیت حرکت'),
        ),
    ]
