# Generated by Django 5.2.7 on 2025-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_failure_dispatch_from_failure_move_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='damage_type',
            field=models.CharField(choices=[('MECHANICAL', 'مکانیکی'), ('ELECTRICAL', 'الکتریکی'), ('BOGIE_CHASSIS', 'شاسی و بوژی'), ('BRAKE', 'ترمز'), ('CABIN_AMENITIES', 'کابین')], max_length=50, verbose_name='Damage Type'),
        ),
    ]
