# Generated by Django 5.2.7 on 2025-11-16 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_repair_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-serviced_date', '-serviced_time'], 'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس\u200cها'},
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('daily', 'روزانه'), ('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('semi_annual', 'شش ماهه'), ('annual', 'سالانه'), ('triennial', 'سه سالانه')], max_length=20, null=True, verbose_name='نوع سرویس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='checklist',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات چک\u200cلیست'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hasOil',
            field=models.BooleanField(default=False, null=True, verbose_name='تعویض روغن'),
        ),
        migrations.AlterField(
            model_name='service',
            name='locomotive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='maintenance.locomotive', verbose_name='لکوموتیو'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviced_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='تاریخ سرویس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviced_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='ساعت سرویس'),
        ),
    ]
