# Generated by Django 5.2.7 on 2025-11-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_service_options_service_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='move_status',
            field=models.CharField(choices=[('ACTIVE', 'گرم / ادامه سیر'), ('DEACTIVE', 'سرد'), ('REPAIR', 'متوقف / اعزام به تعمیرات'), ('INDEPOT', 'دپو/رفع عیب')], default='ACTIVE', max_length=20, verbose_name='وضعیت حرکت'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'سه ماهه'), ('semi_annual', 'شش ماهه'), ('annual', 'سالانه'), ('triennial', 'سه سالانه')], max_length=20, null=True, verbose_name='نوع سرویس'),
        ),
    ]
